config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  ActiveAdmin.routes(self)
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root "products#index"
  resources :products, except: %i[new destroy] do
    resources :order_items, only: %i[create update destroy]
    collection do
      post 'fetch_products', as: :fetch
    end
  end

  resources :orders do
    collection do
      get :checkout
    end
  end

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :comments, as: :commentable
  has_many :category_products
  has_many :products, through: :category_products
end

app/models/category_product.rb
class CategoryProduct < ApplicationRecord
  belongs_to :product
  belongs_to :category

  validates_uniqueness_of :product_id, scope: :category
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :commentable, polymorphic: true
end

app/models/feature.rb
class Feature < ApplicationRecord
  has_many :feature_values
  # has_many :valuables, through: :feature_values, source: :valuable, as: :valuable
  # has_many :valuables, through: :feature_values, source_type: 'StringValue', as: :valuable
  has_many :strs, through: :feature_values, source: :valuable, source_type: 'StringValue'
  has_many :ints, through: :feature_values, source: :valuable, source_type: 'IntegerValue'
  # has_many :vals, through: :feature_values, source: :valuable
end

app/models/feature_value.rb
class FeatureValue < ApplicationRecord
  belongs_to :feature
  belongs_to :valuable, polymorphic: true
end

app/models/integer_value.rb
class IntegerValue < ApplicationRecord
  has_many :feature_values, as: :valuable

  validates_uniqueness_of :value
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user

  has_many :order_items, dependent: :destroy
  has_many :products, through: :order_items

  enum status: %i[in_progress ordered canceled], _prefix: true

  def total_amount
    order_items.includes(:product).map(&:sub_price).sum
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :product
  belongs_to :order

  validates_numericality_of :quantity, greater_than_or_equal_to: 1

  def sub_price
    quantity * product.price
  end
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :comments, as: :commentable

  has_many :category_products
  has_many :categories, through: :category_products

  has_many :product_feature_values
  has_many :feature_values, through: :product_feature_values
  has_many :features, through: :feature_values

  validates_presence_of :title
  validates :images,
            file_size: { less_than_or_equal_to: 100.kilobytes },
            file_content_type: { allow: ['image/jpeg', 'image/png'] },
            length: { maximum: 5 }

  has_many_attached :images do |attachable|
    attachable.variant :thumbnail, resize: '100x100'
    attachable.variant :large, resize: '250x250'
  end

  before_update :send_mail_with_changed_price, if: :price_changed?

  private

  def send_mail_with_changed_price
    ProductJob.set(wait: 10).perform_later(self)
  end
end

app/models/product_feature_value.rb
class ProductFeatureValue < ApplicationRecord
  belongs_to :product
  belongs_to :feature_value

  has_many :features, through: :feature_value

  validates_uniqueness_of :product_id, scope: :features
end

app/models/string_value.rb
class StringValue < ApplicationRecord
  has_many :feature_values, as: :valuable

  validates_uniqueness_of :value
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  after_create :send_welcome_mail

  validates_presence_of :name

  enum role: %i[customer admin], _prefix: true

  private

  def send_welcome_mail
    UserMailer.with(user: self).welcome_mail.deliver_now
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend

  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  helper_method :current_order

  def authenticate_admin_user!
    redirect_to root_path unless current_user.role_admin?
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  private

  def current_order
    Order.find_or_create_by(user: current_user, status: Order.statuses[:in_progress])
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def show
    # @items = current_order.order_items.order(created_at: :asc)
    # order_items = current_order.order_items
    # @items = OrderItems::OrderItemsWithProductsQuery.call(order_items, order_id: current_order.id)
    @items = OrderItems::OrderItemsWithProductsQuery.call(order_id: current_order.id)
  end

  def update
    current_order.update(order_params)

    UserMailer.with(name: current_order.name,
                    email: current_order.email,
                    total_amount: current_order.total_amount)
              .order_created
              .deliver_later

    current_order.status_ordered!
    # result = OrderUpdateService.new(current_order, order_params).call
    # if result.success do
    # end
    redirect_to root_path, notice: 'Order confirmed'
  end

  def checkout; end

  private

  def order_params
    params.require(:order).permit(:name, :email, :phone, :address)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[show edit update]

  def index
    products = Products::SortProductsQuery.call(Product.all, params)
    @categories = Category.left_joins(:products)
                          .select('categories.id, categories.title, COUNT(products.id) products_count')
                          .group(:id)
                          .order(:title)
    @pagy, @products = pagy(products)
  end

  def show; end

  def edit; end

  def update
    if @product.update(product_params)
      redirect_to product_path(@product)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def fetch_products
    ProductFetchJob.set(wait: 10).perform_later
    # redirect_to root_path, notice: "Product was created"
  end

  private

  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:title, :description, images: [])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>🍀 fair-market 🍀</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flash_messages' %>
    <%= yield %>
  </body>
</html>

app/views/shared/_flash_messages.html.erb
<div class="container">
  <% flash.each do |_type, msg| %>
  <div class="alert alert-success mx-auto mt-4 mb-2">
    <%= msg %>
  </div>
  <% end %>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top">
  <div class="container-fluid">
    <%= link_to '🍀', root_path, class: 'navbar-brand text-decoration-none' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#nbMain" aria-controls="nbMain" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="nbMain">
      <ul class="navbar-nav me-auto mb-2">
        <li class="nav-item">
          <%= link_to 'Letters', letter_opener_web_path,
                      target: :_blank,
                      class: 'nav-link link-light' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Fetch Products', fetch_products_path,
                      data: { 'turbo-method': :post },
                      class: 'nav-link link-success' %>
        </li>
        <li class="nav-item">
          <%= link_to_if current_user.present?,
                         'Log Out', destroy_user_session_path,
                         data: { 'turbo-method': :delete },
                         class: 'nav-link link-info' %>
        </li>
        <li class="nav-item">
          <%= link_to_if current_user&.role_admin?,
                         'Admin', admin_dashboard_path,
                         class: 'nav-link link-warning' %>
        </li>
      </ul>
    </div>
  </div>
</nav>