config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  ActiveAdmin.routes(self)
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root "products#index"
  resources :products, except: %i[new destroy] do
    resources :order_items, only: %i[create update destroy]
    collection do
      post 'fetch_products', as: :fetch
    end
  end

  resources :orders do
    collection do
      get :checkout
    end
  end

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :comments, as: :commentable
  has_many :category_products
  has_many :products, through: :category_products
end

app/models/category_product.rb
class CategoryProduct < ApplicationRecord
  belongs_to :product
  belongs_to :category

  validates_uniqueness_of :product_id, scope: :category
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :commentable, polymorphic: true
end

app/models/feature.rb
class Feature < ApplicationRecord
  has_many :feature_values
  # has_many :valuables, through: :feature_values, source: :valuable, as: :valuable
  # has_many :valuables, through: :feature_values, source_type: 'StringValue', as: :valuable
  has_many :strs, through: :feature_values, source: :valuable, source_type: 'StringValue'
  has_many :ints, through: :feature_values, source: :valuable, source_type: 'IntegerValue'
  # has_many :vals, through: :feature_values, source: :valuable
end

app/models/feature_value.rb
class FeatureValue < ApplicationRecord
  belongs_to :feature
  belongs_to :valuable, polymorphic: true
end

app/models/integer_value.rb
class IntegerValue < ApplicationRecord
  has_many :feature_values, as: :valuable

  validates_uniqueness_of :value
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user

  has_many :order_items, dependent: :destroy
  has_many :products, through: :order_items

  enum status: %i[in_progress ordered canceled], _prefix: true

  def total_amount
    order_items.includes(:product).map(&:sub_price).sum
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :product
  belongs_to :order

  validates_numericality_of :quantity, greater_than_or_equal_to: 1

  def sub_price
    quantity * product.price
  end
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :comments, as: :commentable

  has_many :category_products
  has_many :categories, through: :category_products

  has_many :product_feature_values
  has_many :feature_values, through: :product_feature_values
  has_many :features, through: :feature_values

  validates_presence_of :title
  validates :images,
            file_size: { less_than_or_equal_to: 100.kilobytes },
            file_content_type: { allow: ['image/jpeg', 'image/png'] },
            length: { maximum: 5 }

  has_many_attached :images do |attachable|
    attachable.variant :thumbnail, resize: '100x100'
    attachable.variant :large, resize: '250x250'
  end

  before_update :send_mail_with_changed_price, if: :price_changed?

  private

  def send_mail_with_changed_price
    ProductJob.set(wait: 10).perform_later(self)
  end
end

app/models/product_feature_value.rb
class ProductFeatureValue < ApplicationRecord
  belongs_to :product
  belongs_to :feature_value

  has_many :features, through: :feature_value

  validates_uniqueness_of :product_id, scope: :features
end

app/models/string_value.rb
class StringValue < ApplicationRecord
  has_many :feature_values, as: :valuable

  validates_uniqueness_of :value
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  after_create :send_welcome_mail

  validates_presence_of :name

  enum role: %i[customer admin], _prefix: true

  private

  def send_welcome_mail
    UserMailer.with(user: self).welcome_mail.deliver_now
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend

  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  helper_method :current_order

  def authenticate_admin_user!
    redirect_to root_path unless current_user.role_admin?
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  private

  def current_order
    Order.find_or_create_by(user: current_user, status: Order.statuses[:in_progress])
  end

end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController
  before_action :set_product

  def create
    if @order_item
      @order_item.increment!(:quantity)
    else
      @order_item = current_order.order_items.create(product_id: params[:product_id])
    end

    flash[:notice] = "#{ @order_item.product.title } added to the cart."
    redirect_to do
      format.turbo_stream
    end
  end

  def update
    value = params[:method] == "increment" ? 1 : -1
    @order_item.increment(:quantity, value)

    if @order_item.save
      flash.alert = 'Updated'
    else
      flash.alert = @order_item.errors.full_messages[0]
    end
    redirect_to root_path
  end

  def destroy
    @order_item.destroy
    flash.alert = "#{ @order_item.product.title } was delete from the cart."
    redirect_to order_path(current_order)
  end

  private

  def set_product
    @order_item = current_order.order_items.find_by(product: params[:product_id])
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def show
    # @items = current_order.order_items.order(created_at: :asc)
    # order_items = current_order.order_items
    # @items = OrderItems::OrderItemsWithProductsQuery.call(order_items, order_id: current_order.id)
    @items = OrderItems::OrderItemsWithProductsQuery.call(order_id: current_order.id)
  end

  def update
    current_order.update(order_params)

    UserMailer.with(name: current_order.name,
                    email: current_order.email,
                    total_amount: current_order.total_amount)
              .order_created
              .deliver_later

    current_order.status_ordered!
    # result = OrderUpdateService.new(current_order, order_params).call
    # if result.success do
    # end
    redirect_to root_path, notice: 'Order confirmed'
  end

  def checkout; end

  private

  def order_params
    params.require(:order).permit(:name, :email, :phone, :address)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[show edit update]

  def index
    products = Products::SortProductsQuery.call(Product.all, params)
    @categories = Category.left_joins(:products)
                          .select('categories.id, categories.title, COUNT(products.id) products_count')
                          .group(:id)
                          .order(:title)
    @pagy, @products = pagy(products)
  end

  def show; end

  def edit; end

  def update
    if @product.update(product_params)
      redirect_to product_path(@product)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def fetch_products
    ProductFetchJob.set(wait: 10).perform_later
    # redirect_to root_path, notice: "Product was created"
  end

  private

  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:title, :description, images: [])
  end

end

app/controllers/turbo_devise_controller.rb
class TurboDeviseController < ApplicationController
  class Responder < ActionController::Responder
    def to_turbo_stream
      controller.render(options.merge(formats: :html))
    rescue ActionView::MissingTemplate => error
      if get?
        raise error
      elsif has_errors? && default_action
        render rendering_options.merge(formats: :html, status: :unprocessable_entity)
      else
        redirect_to navigation_location
      end
    end
  end

  self.responder = Responder
  respond_to :html, :turbo_stream
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/orders/checkout.html.erb
<div class="container">
  <%= render 'devise/shared/error_messages', resource: current_order %>

  <%= form_for current_order do |f| %>
    <div class="form-group mt-3">
      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control w-75', value: current_user&.email %>
    </div>

    <div class="form-group mt-3">
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control w-75', value: current_user&.name %>
    </div>

    <div class="form-group mt-3">
      <%= f.label :phone %>
      <%= f.phone_field :phone, class: 'form-control w-75' %>
    </div>

    <div class="form-group mt-3">
      <%= f.label :address %>
      <%= f.text_area :address, class: 'form-control w-75' %>
    </div>

    <%= f.submit 'Save', class: 'mt-3' %>
  <% end %>
</div>

app/views/orders/show.html.erb
<div class="conteiner p-3">
  <div class="row row-cols-3 mt-3">
    <% @items.each do |item| %>
      <div class="card m-2 p-1 col-3">
        <h4 class="card-title"><%= item.product_title %></h4>
        <p class="card-text"><%= item.product_description.truncate(100) %></p>
        <p class="text-success">Price: <%= item.product_price %></p>
        <p class="text-success">Quantity: <%= item.quantity %></p>
        <p>
          <%= link_to product_order_item_path(product_id: item.product_id, id: item.id, method: :increment),
                      data: { 'turbo-method': :put },
                      title: '+1',
                      class: 'text-decoration-none' do %>
            <i class="fa-solid fa-circle-plus fa-2x text-success"></i>
          <% end %>
          <%= link_to product_order_item_path(product_id: item.product_id, id: item.id, method: :decrement),
                      data: { 'turbo-method': :put },
                      title: '-1',
                      class: 'text-decoration-none' do %>
            <i class="fa-solid fa-circle-minus fa-2x text-danger"></i>
          <% end %>
          <%= link_to product_order_item_path(product_id: item.product_id, id: item.id),
                      data: { 'turbo-method': :delete },
                      title: 'delete',
                      class: 'text-decoration-none' do %>
            <i class="fa-solid fa-trash-can-arrow-up fa-2x text-warning"></i>
          <% end %>
        </p>
      </div>
    <% end %>
  </div>
  <%= link_to 'Complete Order', checkout_orders_path,
              class: "btn btn-outline-success" %>
</div>

app/views/products/_filters.html.erb
<%= form_tag products_path, method: :get do %>
  <%= hidden_field_tag :price, params[:price] if params[:price].present? %>

  <div class="categories my-3">
    <p><b>Categories:</b></p>
    <ul class="category">
      <% @categories.each do |category| %>
        <li>
          <%= check_box_tag 'category_ids[]',
                            category.id,
                            !!params[:category_ids]&.include?(category.id.to_s),
                            id: "cb#{ category.id }",
                            remote: true %>
          <label for="cb#{ category.id }" class="text-dark"><%= category.title %></label>
          <b class="text-dark"><%= category.products_count %></b>
        </li>
      <% end %>
    </ul>
  </div>

  <div class="price my-3">
    <p><b>Price:</b></p>
    <%= text_field_tag :min_price, nil, class: 'form-control', placeholder: 'Min', value: params[:min_price] %>
    <br>
    <%= text_field_tag :max_price, nil, class: 'form-control', placeholder: 'Max', value: params[:max_price] %>
    <hr>
    <%= submit_tag 'Find', class: 'btn btn-success' %>
  </div>
<% end %>

app/views/products/_products.html.erb
<div class="row row-cols-5 mt-3">
  <% @products.each do |product| %>
    <div class="card m-2 p-1">
      <h4 class="card-title"><%= product.title %></h4>
      <p class="card-text"><%= product.description.truncate(100) %></p>
      <p class="text-success">Price: <%= product.price %></p>
      <p>
        <%= link_to 'Add to Cart', product_order_items_path(product),
                    data: { "turbo-method": :post },
                    class: 'btn btn-outline-success rounded-pill' %>
      </p>
    </div>
  <% end %>
</div>

app/views/products/_sorts.html.erb
<div class="row">
  <%= link_to 'Cheaper', products_path(price: :asc,
                                       min_price: params[:min_price],
                                       max_price: params[:max_price],
                                       category_ids: params[:category_ids]),
              class: 'col-1' %>
  <%= link_to 'More expensive', products_path(price: :desc,
                                              min_price: params[:min_price],
                                              max_price: params[:max_price],
                                              category_ids: params[:category_ids]),
              class: 'col' %>
</div>

app/views/products/edit.html.erb
<div class="container">
  <%= render 'devise/shared/error_messages', resource: @product %>

  <%= form_for @product do |f| %>
    <div class="form-group mt-3">
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control w-75' %>
    </div>

    <div class="form-group mt-3">
      <%= f.label :description %>
      <%= f.text_area :description, class: 'form-control w-75' %>
    </div>

    <div class="form-group mt-3">
      <%= f.label :image %>
      <%= f.file_field :images, class: 'form-control w-75', multiple: true %>
    </div>

    <%= f.submit 'Save', class: 'mt-3' %>
  <% end %>
</div>

app/views/products/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-1 col-md-3 col-xl-2 px-sm-2 p-0 navbar-light bg-light">
        <%= render 'filters' %>
    </div>
    <div class="col">
      <%= render 'sorts' %>
      <%= render 'products' %>
    </div>
    <div class="col-1 p-0">
      <% if current_order.order_items.present? %>
        <nav class="navbar mt-5 ms-5 sticky-top text-center">
          <%= link_to order_path(current_order) do %>
            <div class="class spinner-border text-success">
              <i class="fa-solid fa-cart-arrow-down fa-3x link-warning"></i>
              <span class="position-absolute top-0 start-100 translate-top badge rounded-pill bg-danger">
                <%= current_order.order_items.count %>
              </span>
            </div>
          <% end %>
        </nav>
      <% end %>
    </div>
  </div>
  <nav class="navbar bg-light sticky-bottom">
    <%== pagy_nav(@pagy) %>
  </nav>
</div>

app/views/products/show.html.erb
<div>
  <% @product.images.each do |image| %>
    <%= image_tag image.variant(:large) %>
  <% end %>
</div>
<div>
  <%= @product.description %>

  <%= link_to 'Root', root_path, class: 'btn btn-success' %>
  <%= link_to 'Destroy', product_path(@product), data: { 'turbo-method': :delete } %>
</div>